#!/usr/bin/env bash

set -euo pipefail

SERVER_BINARY=$1
LOCAL_PORT=$2
REMOTE_PORT=$3

# Tell the OS itself to ignore any incoming traffic on my chosen local port - I want to handle that myself!
echo "setting up iptables..."
iptables -v -t filter --append INPUT --protocol tcp --dport $LOCAL_PORT -j DROP

# disable MallocNanoZone as a fix for this issue on macOS
# https://stackoverflow.com/questions/69861144/get-an-error-as-a-out40780-0x1130af600-malloc-nano-zone-abandoned-due-to-in
echo "starting server..."
MallocNanoZone=0 $SERVER_BINARY

iptables_cleanup() {
  echo "cleaning up iptables..."
  iptables -v -t filter --delete INPUT --protocol tcp --dport $LOCAL_PORT -j DROP
}

trap 'iptables_cleanup' EXIT

sleep 100
